### ISSUE TITLE
Mod not working at all

### ISSUE THREAD

**Issue by guernzilla** [goatgirlclover/BRC-MusicCurator#1]
Mod is not working at all,  will not initialize in Bepin. Mod installed via thunderstore, on game version 1.0.19735
Screenshot of bepin log attached

![29f4fe947a2368b19d7d11a611080867](https://github.com/scoopds/BRC-MusicCurator/assets/13027588/fed21db0-788c-47a8-ac73-2e6135b1bc08)

**Comment by goatgirlclover** [comment]
update to the latest version of the game
